### ISSUE TITLE
Code block's font is not set for ja-jp

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs.ja-jp#241]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/feedback/issues/1575
so we can work it in the correct repository.

@0giso commented 2 days ago
**Describe the bug**
Code block's font is not set for ja-jp. Which font is used depends on the browser.

**To Reproduce**

1. Go to https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.2. (Any pages under https://docs.microsoft.com/ja-jp/ can reproduce.)
2. See code block. Font depends on the browser. (Chrome, Edge, IE).

**Expected behavior**
Use fonts similar to consolas for code blocks in any languages, any browsers.

**Desktop (please complete the following information):**

OS: Windows 10 17134.799
Browser Edge, IE11

**Additional context**
AWS document use consolas for code blocks in any language, any browsers. This is my expectation for docs.microsoft.com.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/es_es/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/fr_fr/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/it_it/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/de_de/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/ko_kr/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/pt_br/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/zh_cn/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/zh_tw/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 97234f18-4009-0ebf-a379-9b63125529cd
* Version Independent ID: 1bf4792d-dab4-e03d-2021-3dcdcaff6a0f
* Content: [ASP.NET Core アプリの Details メソッドと Delete メソッドの確認](https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/details.md](https://github.com/aspnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/tutorials/first-mvc-app/details.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by 0giso** [comment]
@Rick-Anderson @CeciAc Yes, followings are other examples which has same issue.
https://docs.microsoft.com/ja-jp/dotnet/csharp/tour-of-csharp/program-structure
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-dotnet-dependency-injection

**Comment by Rick-Anderson** [comment]
@CeciAc  recommend you close this issue because it's a problem with all the docs.ms.com - not just the asp.net docs.  The original issue is the correct place to report this.

**Comment by CeciAc** [comment]
Closing this issue, following the issue up at its original repo: https://github.com/MicrosoftDocs/feedback/issues/1575
