### ISSUE TITLE
Safelist should translate as "セーフリスト".

### ISSUE THREAD

**Issue by workstyletips** [aspnet/AspNetCore.Docs.ja-jp#257]
Safelist is translated as "セーフセーフ".
Safe is "セーフ", so "セーフセーフ" means "Safesafe".
Therefore, in "セーフセーフ", people can not understand the meaning correctly.
Safelist should translate as "セーフリスト".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [ASP.NET Core のクライアント IP セーフセーフ](https://docs.microsoft.com/ja-jp/aspnet/core/security/ip-safelist?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/aspnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @workstyletips
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @workstyletips 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/aspnet/core/security/ip-safelist?view=aspnetcore-3.0#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
