### ISSUE TITLE
Incorrect translations - Angular and React App

### ISSUE THREAD

**Issue by 0x6797** [aspnet/AspNetCore.Docs.ja-jp#288]
s/角度アプリ/Angular アプリ/
s/反応アプリ/React アプリ/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [ASP.NET Core でのシングルページアプリの認証の概要](https://docs.microsoft.com/ja-jp/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @0x6797
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by 0x6797** [comment]
Thanks for your response.

**Comment by ticianaciminari** [comment]
@0x6797 様: 

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 

サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム
